const ACTION_TYPES = {
  BETS: {
    GET_GAME_DATA: 'BETS_GET_GAME_DATA',
    GET_LOADING: 'BETS_GET_LOADING',
    EXIT_GAME: 'BETS_EXIT_GAME'
  },
  WATCH: {
    GET_LOADING_TEAMS: 'WATCH_GET_LOADING_TEAMS',
    GET_ALL_TEAMS_LIST: 'GET_ALL_TEAMS_LIST',
    GET_TEAMS_LIST: 'WATCH_GET_TEAMS_LIST',
    GET_TEAMS_GAME_DATA: 'WATCH_GET_TEAMS_GAME_DATA',
    GET_SELECTIONS_GAME_DATA: 'WATCH_GET_SELECTIONS_GAME_DATA',
    GET_LOADING_SELECTIONS: 'WATCH_GET_LOADING_SELECTIONS'
  },
  FEEDBACK: {
    GET_LOADING: 'FEEDBACK_GET_LOADING',
    SUBMIT_FEEDBACK: 'FEEDBACK_SUBMIT_FEEDBACK'
  }
};

export { ACTION_TYPES };
