export const Routes = {
  // no auth
  Splash: 'Splash',
  Login: 'Login',
  Register: 'Register',
  EmailRegister: 'EmailRegister',
  Dashboard: 'Dashboard',
  DrawerRoute: 'DrawerRoute',
  TabRoute: 'TabRoute',
  OBI: 'OBI',
  OBIMoney: 'OBIMoney',
  OBIBooks: 'OBIBooks',
  OBILineRater: 'OBILineRater',
  OBIWeight: 'OBIWeight',
  Schedule: 'Schedule',
  LineRater: 'LineRater',
  Watch: 'Watch',
  MyTeam: 'MyTeam',
  Partner: 'Partner',
  UserMenu: 'UserMenu',
  Notification: 'Notification',
  Subscription: 'Subscription',
  SubscriptionLoading: 'SubscriptionLoading',
  Introduction: 'Introduction',
  MyAccount: 'MyAccount',
  FAQs: 'FAQs',
  ContactUs: 'ContactUs',
  Privacy: 'Privacy',
  Feedback: 'Feedback',
  Logout: 'Logout',
  HowToUse: 'HowToUse'
};
